create table "public"."asset" (
  "id_asset"   integer                generated by default as identity not null,
  "asset_code" character varying(255) not null,
  "id_ruangan" integer                not null,
  constraint "asset_asset_code_key" unique (asset_code),
  constraint "asset_pkey" primary key (id_asset),
  constraint "asset_id_ruangan_fkey" foreign key (id_ruangan) references public.unit(id)
);

alter table "public"."asset"
  enable row level security;

alter table "public"."asset"
  add column "status" public.asset_status_enum not null;

create index idx_asset_id_ruangan on public.asset using btree (id_ruangan);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."asset" to "anon", "authenticated", "postgres", "service_role";
