create table "public"."knowledge_article" (
  "id"          integer                generated by default as identity not null,
  "id_categori" integer                not null,
  "judul"       character varying(255) not null,
  "content"     text                   not null,
  "video_url"   character varying(500),
  "helpful"     integer                not null default 0,
  "unhelpful"   integer                not null default 0,
  constraint "knowledge_article_pkey" primary key (id),
  constraint "knowledge_article_id_categori_fkey" foreign key (id_categori) references public.knowledge_kategori(id)
);

alter table "public"."knowledge_article"
  enable row level security;

alter table "public"."knowledge_article"
  add column "level" public.knowledge_level_enum not null;

create index idx_knowledge_article_id_categori on public.knowledge_article using btree (id_categori);

create index idx_knowledge_article_level on public.knowledge_article using btree (level);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."knowledge_article" to "anon", "authenticated", "postgres", "service_role";
