create table "public"."knowledge_kategori" (
  "id"            integer                generated by default as identity not null,
  "nama_kategori" character varying(255),
  constraint "knowledge_kategori_pkey" primary key (id)
);

alter table "public"."knowledge_kategori"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."knowledge_kategori" to "anon", "authenticated", "postgres", "service_role";
