create table "public"."login" (
  "id"       integer                generated by default as identity not null,
  "Nama"     character varying(100),
  "email"    character varying(200),
  "password" character varying(200),
  constraint "login_pkey" primary key (id)
);

alter table "public"."login"
  enable row level security;

alter table "public"."login"
  add column "role" public.login_role_enum;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."login" to "anon", "authenticated", "postgres", "service_role";
