create table "public"."tiket" (
  "id"        integer                generated by default as identity not null,
  "judul"     character varying(255) not null,
  "categori"  integer                not null,
  "ruangan"   integer                not null,
  "deskripsi" text                   not null,
  "akun"      integer                not null,
  "teknisi"   integer,
  "solusi"    text,
  constraint "tiket_akun_fkey" foreign key (akun) references public.login(id),
  constraint "tiket_categori_fkey" foreign key (categori) references public.knowledge_kategori(id),
  constraint "tiket_pkey" primary key (id),
  constraint "tiket_teknisi_fkey" foreign key (teknisi) references public.login(id),
  constraint "tiket_ruangan_fkey" foreign key (ruangan) references public.unit(id)
);

alter table "public"."tiket"
  enable row level security;

alter table "public"."tiket"
  add column "prioritas" public.priority_level_enum not null;

alter table "public"."tiket"
  add column "status" public.tiket_status_enum not null default 'NEW'::public.tiket_status_enum;

alter table "public"."tiket"
  add constraint "tiket_prioritas_fkey" foreign key (prioritas) references public.level(level);

create index idx_tiket_akun on public.tiket using btree (akun);

create index idx_tiket_categori on public.tiket using btree (categori);

create index idx_tiket_prioritas on public.tiket using btree (prioritas);

create index idx_tiket_ruangan on public.tiket using btree (ruangan);

create index idx_tiket_teknisi on public.tiket using btree (teknisi);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."tiket" to "anon", "authenticated", "postgres", "service_role";
