create table "public"."troubleshooting" (
  "id"       integer generated by default as identity not null,
  "id_tiket" integer not null,
  "lampiran" integer not null,
  "tindakan" text    not null,
  "hasil"    text    not null,
  constraint "troubleshooting_id_tiket_fkey" foreign key (id_tiket) references public.tiket(id) on update cascade on delete cascade,
  constraint "troubleshooting_pkey" primary key (id)
);

alter table "public"."troubleshooting"
  enable row level security;

create index idx_troubleshooting_id_tiket on public.troubleshooting using btree (id_tiket);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."troubleshooting" to "anon", "authenticated", "postgres", "service_role";
