create table "public"."unit" (
  "id"      integer                generated by default as identity not null,
  "ruangan" character varying(255),
  constraint "unit_pkey" primary key (id)
);

alter table "public"."unit"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."unit" to "anon", "authenticated", "postgres", "service_role";
